version: '3.8'
services:
  web_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    network_mode: "host"  # Use host network mode for better performance and direct access
